### ISSUE TITLE
Any plan for a Lora version ?

### ISSUE THREAD

**Issue by vincegre** [FindMyCat/hardware-files#1]
Hi

Thanks for sharing that fantastic project :) Do you plan to develop a LORA version ? It would make it even cheaper and lasts longer on a battery charge.

Thanks

Vincèn

**Comment by ChitlangeSahas** [comment]
@vincegre Thank you for reaching out, I am glad you like it!

In terms of LORA version, it is a possibility. I have been thinking about a fusion of LORA and LTE. I think for me constant connectivity with an infinite range was non-negotiable, so LORA is a possibility along with LTE and fallback to LTE when out of LORA coverage or something. 

PS. we have a [slack community](https://join.slack.com/t/findmycat/shared_invite/zt-21wo1f57m-zVcXlUkAvFmwDA3k5uYysw) to discuss all hardware improvements, if you'd be interested :)

**Comment by vincegre** [comment]
> In terms of LORA version, it is a possibility. I have been thinking about a fusion of LORA and LTE. I think for me constant connectivity with an infinite range was non-negotiable, so LORA is a possibility along with LTE and fallback to LTE when out of LORA coverage or something.


Well Lora is quite infinite range as a single gateway can cover as much as 20/30km around quite easily ;) and also if only Lora it allows it to last very long time on battery ;)

> PS. we have a [slack community](https://join.slack.com/t/findmycat/shared_invite/zt-21wo1f57m-zVcXlUkAvFmwDA3k5uYysw) to discuss all hardware improvements, if you'd be interested :)

Thanks but not using Slack, too much waste of time :-1:

**Comment by vincegre** [comment]
wow ticket closed straight, great :-1:
